name: tests (Camel)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build with make
      run: make
    # - name: make test
      # run: make test

  build-windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build with make
      run: make windows


